basic.forever(function () {
    if (input.buttonIsPressed(Button.B)) {
        pins.digitalWritePin(DigitalPin.P1, 1)
        basic.pause(200)
        pins.digitalWritePin(DigitalPin.P1, 0)
        basic.pause(200)
        pins.digitalWritePin(DigitalPin.P1, 1)
        basic.pause(200)
        pins.digitalWritePin(DigitalPin.P1, 0)
        basic.pause(200)
        pins.digitalWritePin(DigitalPin.P1, 1)
        basic.pause(200)
        pins.digitalWritePin(DigitalPin.P1, 0)
        basic.pause(200)
    }
})
basic.forever(function () {
    if (input.buttonIsPressed(Button.A)) {
        music.playTone(277, music.beat(BeatFraction.Whole))
        basic.pause(200)
        music.playTone(311, music.beat(BeatFraction.Whole))
        basic.pause(200)
        music.playTone(208, music.beat(BeatFraction.Whole))
        basic.pause(100)
        music.playTone(311, music.beat(BeatFraction.Whole))
        basic.pause(200)
        music.playTone(349, music.beat(BeatFraction.Whole))
        basic.pause(100)
        music.playTone(415, music.beat(BeatFraction.Quarter))
        music.playTone(370, music.beat(BeatFraction.Quarter))
        music.playTone(349, music.beat(BeatFraction.Quarter))
        music.playTone(311, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Whole))
        basic.pause(100)
        music.playTone(311, music.beat(BeatFraction.Whole))
        basic.pause(100)
        music.playTone(208, music.beat(BeatFraction.Double))
        music.playTone(415, music.beat(BeatFraction.Quarter))
        music.playTone(370, music.beat(BeatFraction.Quarter))
        music.playTone(349, music.beat(BeatFraction.Quarter))
        music.playTone(311, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Whole))
        basic.pause(200)
        music.playTone(311, music.beat(BeatFraction.Whole))
        basic.pause(200)
        music.playTone(208, music.beat(BeatFraction.Whole))
        basic.pause(100)
        music.playTone(311, music.beat(BeatFraction.Whole))
        basic.pause(200)
        music.playTone(349, music.beat(BeatFraction.Whole))
        basic.pause(100)
        music.playTone(415, music.beat(BeatFraction.Quarter))
        music.playTone(370, music.beat(BeatFraction.Quarter))
        music.playTone(349, music.beat(BeatFraction.Quarter))
        music.playTone(311, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Whole))
        basic.pause(100)
        music.playTone(311, music.beat(BeatFraction.Whole))
        basic.pause(100)
        music.playTone(208, music.beat(BeatFraction.Double))
        music.playTone(277, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Quarter))
        basic.pause(200)
        music.playTone(277, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Quarter))
        basic.pause(500)
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(208, music.beat(BeatFraction.Double))
        basic.pause(200)
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(208, music.beat(BeatFraction.Half))
        music.playTone(415, music.beat(BeatFraction.Whole))
        music.playTone(415, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Double))
        basic.pause(200)
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(208, music.beat(BeatFraction.Double))
        basic.pause(200)
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(208, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Double))
        basic.pause(200)
        music.playTone(277, music.beat(BeatFraction.Double))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(208, music.beat(BeatFraction.Half))
        music.playTone(208, music.beat(BeatFraction.Double))
        basic.pause(200)
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Double))
        basic.pause(200)
        music.playTone(233, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Quarter))
        music.playTone(233, music.beat(BeatFraction.Quarter))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Double))
        basic.pause(200)
        music.playTone(208, music.beat(BeatFraction.Quarter))
        music.playTone(233, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Quarter))
        music.playTone(208, music.beat(BeatFraction.Quarter))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Quarter))
        music.playTone(233, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(208, music.beat(BeatFraction.Half))
        music.playTone(175, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Double))
        basic.pause(200)
        music.playTone(233, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Quarter))
        music.playTone(233, music.beat(BeatFraction.Quarter))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(349, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Double))
        basic.pause(200)
        music.playTone(208, music.beat(BeatFraction.Quarter))
        music.playTone(233, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Quarter))
        music.playTone(208, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Whole))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(208, music.beat(BeatFraction.Quarter))
        music.playTone(233, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Quarter))
        music.playTone(208, music.beat(BeatFraction.Quarter))
        music.playTone(277, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Half))
        music.playTone(233, music.beat(BeatFraction.Half))
        music.playTone(208, music.beat(BeatFraction.Half))
        music.playTone(175, music.beat(BeatFraction.Half))
        music.playTone(311, music.beat(BeatFraction.Half))
        music.playTone(277, music.beat(BeatFraction.Double))
    }
})
basic.forever(function () {
    if (true) {
        pins.servoWritePin(AnalogPin.P2, 180)
    } else {
        pins.servoWritePin(AnalogPin.P2, 0)
    }
})
